### ISSUE TITLE
Stops working within a couple of hours

### ISSUE THREAD

**Issue by dkduck** [gruijter/com.gruijter.virtualradar#4]
Hi

Think I found the problem, been running stable now, then I added a numer 2 radar, and then - everything stops working.

Deleted both radars, deleted logfile, restartede app
Added new radar, with new name (importent, can´t use name that have been used before)
Everything works like a charm again

Just to inform you :-)

**Comment by gruijter** [comment]
super, thx for the feedback!

I fixed the naming issue in the next release (2.0.2).

In v2.0.2 I also decided to add clarification to the filter device settings. If you enable both 'In Air' and 'On Ground' you will wind up with no planes (since you cannot be both on the ground AND in the air). Maybe that is what happened with your settings. I have no problem adding multiple radars.
